# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testapp4

on:
  push:
    branches:
      - proj
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_818966fc5b684545892d360da8e9eac8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_91a9a534248842758aca5cf94d211957 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_818966fc5b684545892d360da8e9eac8 }}/hipoint/app:${{ github.sha }}
        file: ./test_project/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testapp4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ed8050df7fd34d5fa8d7127221a8c50c }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_818966fc5b684545892d360da8e9eac8 }}/hipoint/app:${{ github.sha }}'